version: '3.7'

services:
  app:
    container_name: app
    image: iwona007/virtualmarines:1.0
    build:
      context: .
      args:
        JAR_FILE: target/*.jar
    networks:
      - marine_network
    ports:
      - "9000:9090"
    volumes:
      - ./logs:/var/www/logs
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marines
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    container_name: db
    image: postgres:13
    restart: always
    networks:
      - marine_network
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=marines
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  marine_network:
    driver: bridge

